### ISSUE TITLE
[STCATP][Forms] Changes in Existing forms

### ISSUE THREAD

**Issue by arjunk** [avniproject/stcatp#34]
There are some changes suggested by client to be done on some forms

**Child Friendly Corner** 

- [x]  Checklist and Functionality Check will be 2 sections in the form
- [x]  Form will be scheduled once after registration and then every 3 months
- [x]  Form will have one auto-calculated field 'Functionality Status' using Decision rule

Refer : https://docs.google.com/spreadsheets/d/1xxaaLZNopcw15uElU0-zxEIQNTLSFngc/edit#gid=305957659

**Training**
Each Training form will have following additional questions

- [x] There would be an option to enter Average Pre Test Score in the form
- [x] There would be an option to enter Average Post Test Score in the form
- [x] Number of participants whose score has increased in post test in comparison to pre test - Male
- [x] Number of participants whose score has increased in post test in comparison to pre test - Female
- [x] Number of participants whose score has increased in post test in comparison to pre test - Boys
- [x] Number of participants whose score has increased in post test in comparison to pre test - Girls

Refer : https://docs.google.com/spreadsheets/d/1jSTieCjWloqFeKpyTJR80QL7OdmpFDh3/edit#gid=1212443793

**Comment by garimadosar5** [comment]
QA Notes - 
Child friendly corner checklist form - On edit it is showing invalid date for scheduled visit.
![Screenshot_2021-09-01-21-38-17-75_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/b40bc3c7-6b02-4c1b-ad4d-3b13cb36cd31)


**Looks like u r editing an unplanned visit. Since this will be planned visit this change onwards, So please check using a planned visit.**
